### ISSUE TITLE
No driver for TP-Link AX1800/Archer TX20U

### ISSUE THREAD

**Issue by nukul4r** [lwfinger/rtl8852au#91]
Hi,

thanks for the repo and you efforts. I recently bought TP-Link AX1800, which I cannot get working. I installed the driver via https://aur.archlinux.org/packages/rtl8852au-dkms-git.

It seems to be a relatively new model or revision, and uses `RTL8832AU` (according to this source: https://geizhals.de/tp-link-ax1800-archer-tx20u-a3154504.html#data, the official website does not mention the chip: https://www.tp-link.com/de/support/download/archer-tx20u).

My USB ID is not matching the ones you mention for this model, `lsusb` gives me

```
Bus 005 Device 005: ID 35bc:0100 Realtek 802.11ac WLAN Adapter
```

whereas you mention the IDs `2357:013f` and `2357:0141`.

Looking at `inxi -Fxz`, it shows up as  network device, but the driver is missing (see `Device-2`):
```
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: ASUSTeK RTL8111H driver: r8169 v: kernel port: f000 bus-ID: 04:00.0
  IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: <filter>
  Device-2: Realtek 802.11ac WLAN Adapter driver: N/A type: USB
    bus-ID: 5-2:5
```

I also made sure it's not mounted as storage, I did `sudo usb_modeswitch -J -v 35bc -p 0100`, and it returned: 
```
Look for default devices ...
 Found devices in default mode (1)
Access device 005 on bus 005
Get the current device configuration ...
Current configuration number is 1
Use interface number 0
 with class 255
Error: can't use storage command in MessageContent with interface 0; interface class is 255, expected 8. Abort
```

Another interesting point is, that it's named `802.11ac`, however it should be an `ax` device.

Do you have an idea what I can try, or is it just that the stick is not supported (yet)? Any help is appreciated, I can still return it though, if there is nothing to be done. Thanks a lot!
